-- WARNING: This schema is for context only and is not meant to be run.
-- Table order and constraints may not be valid for execution.

CREATE TABLE public.ai_configurations (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  provider USER-DEFINED NOT NULL,
  model_name character varying NOT NULL CHECK (length(TRIM(BOTH FROM model_name)) > 0),
  api_endpoint character varying,
  api_key text,
  max_tokens integer DEFAULT 2000 CHECK (max_tokens >= 100 AND max_tokens <= 10000),
  temperature numeric DEFAULT 0.7 CHECK (temperature >= 0.0 AND temperature <= 2.0),
  is_active boolean DEFAULT true,
  created_by uuid,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT ai_configurations_pkey PRIMARY KEY (id),
  CONSTRAINT fk_ai_config_created_by FOREIGN KEY (created_by) REFERENCES public.users(id)
);
CREATE TABLE public.ai_generation_logs (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  user_id uuid,
  provider USER-DEFINED NOT NULL,
  model_name character varying NOT NULL,
  prompt text NOT NULL,
  response text,
  tokens_used integer DEFAULT 0 CHECK (tokens_used >= 0),
  request_type character varying NOT NULL,
  entity_type character varying,
  entity_id uuid,
  success boolean DEFAULT false,
  error_message text,
  execution_time_ms integer CHECK (execution_time_ms IS NULL OR execution_time_ms >= 0),
  created_at timestamp with time zone DEFAULT now(),
  CONSTRAINT ai_generation_logs_pkey PRIMARY KEY (id),
  CONSTRAINT fk_ai_logs_user_id FOREIGN KEY (user_id) REFERENCES public.users(id)
);
CREATE TABLE public.ai_requests (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  user_id uuid NOT NULL,
  provider character varying NOT NULL,
  model_name character varying NOT NULL,
  prompt text NOT NULL,
  response text,
  tokens_used integer,
  request_type character varying NOT NULL CHECK (request_type::text = ANY (ARRAY['control_generation'::character varying, 'risk_assessment'::character varying, 'audit_plan'::character varying, 'finding_analysis'::character varying]::text[])),
  entity_id uuid,
  created_at timestamp with time zone DEFAULT now(),
  CONSTRAINT ai_requests_pkey PRIMARY KEY (id),
  CONSTRAINT ai_requests_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.users(id)
);
CREATE TABLE public.approval_requests (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  entity_type character varying NOT NULL CHECK (entity_type::text = ANY (ARRAY['audit'::character varying, 'finding'::character varying, 'control'::character varying, 'risk'::character varying]::text[])),
  entity_id uuid NOT NULL,
  workflow_id uuid,
  current_step integer DEFAULT 1,
  status character varying DEFAULT 'pending_approval'::character varying CHECK (status::text = ANY (ARRAY['pending_approval'::character varying, 'approved'::character varying, 'rejected'::character varying, 'revision_required'::character varying]::text[])),
  requested_by uuid,
  requested_at timestamp with time zone DEFAULT now(),
  completed_at timestamp with time zone,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT approval_requests_pkey PRIMARY KEY (id),
  CONSTRAINT approval_requests_workflow_id_fkey FOREIGN KEY (workflow_id) REFERENCES public.workflows(id),
  CONSTRAINT approval_requests_requested_by_fkey FOREIGN KEY (requested_by) REFERENCES public.users(id)
);
CREATE TABLE public.audit_comments (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  audit_id uuid NOT NULL,
  parent_comment_id uuid,
  comment_text text NOT NULL,
  comment_type character varying DEFAULT 'general'::character varying,
  is_internal boolean DEFAULT true,
  priority USER-DEFINED DEFAULT 'low'::priority_level,
  status character varying DEFAULT 'open'::character varying,
  created_by uuid NOT NULL,
  assigned_to uuid,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  resolved_at timestamp with time zone,
  resolved_by uuid,
  CONSTRAINT audit_comments_pkey PRIMARY KEY (id),
  CONSTRAINT audit_comments_parent_comment_id_fkey FOREIGN KEY (parent_comment_id) REFERENCES public.audit_comments(id),
  CONSTRAINT audit_comments_audit_id_fkey FOREIGN KEY (audit_id) REFERENCES public.audits(id),
  CONSTRAINT audit_comments_assigned_to_fkey FOREIGN KEY (assigned_to) REFERENCES public.users(id),
  CONSTRAINT audit_comments_created_by_fkey FOREIGN KEY (created_by) REFERENCES public.users(id),
  CONSTRAINT audit_comments_resolved_by_fkey FOREIGN KEY (resolved_by) REFERENCES public.users(id)
);
CREATE TABLE public.audit_logs (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  user_id uuid,
  action character varying NOT NULL,
  entity_type character varying NOT NULL,
  entity_id uuid NOT NULL,
  old_values jsonb,
  new_values jsonb,
  ip_address inet,
  user_agent text,
  created_at timestamp with time zone DEFAULT now(),
  CONSTRAINT audit_logs_pkey PRIMARY KEY (id),
  CONSTRAINT audit_logs_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.users(id)
);
CREATE TABLE public.audit_notifications (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  audit_id uuid NOT NULL,
  recipient_id uuid NOT NULL,
  notification_type character varying NOT NULL,
  title character varying NOT NULL,
  message text NOT NULL,
  is_read boolean DEFAULT false,
  priority USER-DEFINED DEFAULT 'medium'::priority_level,
  action_required boolean DEFAULT false,
  action_url text,
  sent_at timestamp with time zone DEFAULT now(),
  read_at timestamp with time zone,
  expires_at timestamp with time zone,
  CONSTRAINT audit_notifications_pkey PRIMARY KEY (id),
  CONSTRAINT audit_notifications_recipient_id_fkey FOREIGN KEY (recipient_id) REFERENCES public.users(id),
  CONSTRAINT audit_notifications_audit_id_fkey FOREIGN KEY (audit_id) REFERENCES public.audits(id)
);
CREATE TABLE public.audit_objectives (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  audit_id uuid NOT NULL,
  objective_text text NOT NULL,
  objective_order integer NOT NULL CHECK (objective_order > 0),
  ai_generated boolean DEFAULT false,
  ai_confidence_score numeric,
  completion_status character varying DEFAULT 'pending'::character varying,
  completion_notes text,
  completed_by uuid,
  completed_at timestamp with time zone,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT audit_objectives_pkey PRIMARY KEY (id),
  CONSTRAINT audit_objectives_completed_by_fkey FOREIGN KEY (completed_by) REFERENCES public.users(id),
  CONSTRAINT audit_objectives_audit_id_fkey FOREIGN KEY (audit_id) REFERENCES public.audits(id)
);
CREATE TABLE public.audit_phases (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  audit_id uuid NOT NULL,
  phase_name character varying NOT NULL,
  phase_description text,
  phase_order integer NOT NULL CHECK (phase_order > 0),
  planned_start_date date,
  planned_end_date date,
  actual_start_date date,
  actual_end_date date,
  status character varying DEFAULT 'pending'::character varying,
  completion_percentage numeric DEFAULT 0 CHECK (completion_percentage >= 0::numeric AND completion_percentage <= 100::numeric),
  phase_lead_id uuid,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT audit_phases_pkey PRIMARY KEY (id),
  CONSTRAINT audit_phases_audit_id_fkey FOREIGN KEY (audit_id) REFERENCES public.audits(id),
  CONSTRAINT audit_phases_phase_lead_id_fkey FOREIGN KEY (phase_lead_id) REFERENCES public.users(id)
);
CREATE TABLE public.audit_planning_documents (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  audit_id uuid NOT NULL,
  document_type character varying NOT NULL,
  document_name character varying NOT NULL,
  file_path text,
  file_size bigint CHECK (file_size >= 0),
  mime_type character varying,
  version integer DEFAULT 1 CHECK (version > 0),
  uploaded_by uuid NOT NULL,
  uploaded_at timestamp with time zone DEFAULT now(),
  is_current_version boolean DEFAULT true,
  CONSTRAINT audit_planning_documents_pkey PRIMARY KEY (id),
  CONSTRAINT audit_planning_documents_audit_id_fkey FOREIGN KEY (audit_id) REFERENCES public.audits(id),
  CONSTRAINT audit_planning_documents_uploaded_by_fkey FOREIGN KEY (uploaded_by) REFERENCES public.users(id)
);
CREATE TABLE public.audit_security_log (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  user_id uuid,
  audit_id uuid,
  action character varying NOT NULL,
  resource_type character varying NOT NULL,
  resource_id uuid,
  ip_address inet,
  user_agent text,
  details jsonb,
  created_at timestamp with time zone DEFAULT now(),
  CONSTRAINT audit_security_log_pkey PRIMARY KEY (id),
  CONSTRAINT audit_security_log_audit_id_fkey FOREIGN KEY (audit_id) REFERENCES public.audits(id),
  CONSTRAINT audit_security_log_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.users(id)
);
CREATE TABLE public.audit_status_history (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  audit_id uuid NOT NULL,
  old_status character varying,
  new_status character varying NOT NULL,
  changed_by uuid NOT NULL,
  changed_at timestamp with time zone DEFAULT now(),
  change_reason text,
  additional_notes text,
  CONSTRAINT audit_status_history_pkey PRIMARY KEY (id),
  CONSTRAINT audit_status_history_audit_id_fkey FOREIGN KEY (audit_id) REFERENCES public.audits(id),
  CONSTRAINT audit_status_history_changed_by_fkey FOREIGN KEY (changed_by) REFERENCES public.users(id)
);
CREATE TABLE public.audit_team_members (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  audit_id uuid NOT NULL,
  user_id uuid NOT NULL,
  role character varying NOT NULL,
  responsibilities text,
  allocated_hours numeric DEFAULT 0 CHECK (allocated_hours >= 0::numeric),
  actual_hours numeric DEFAULT 0 CHECK (actual_hours >= 0::numeric),
  added_at timestamp with time zone DEFAULT now(),
  added_by uuid NOT NULL,
  removed_at timestamp with time zone,
  removed_by uuid,
  is_active boolean DEFAULT true,
  CONSTRAINT audit_team_members_pkey PRIMARY KEY (id),
  CONSTRAINT audit_team_members_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.users(id),
  CONSTRAINT audit_team_members_added_by_fkey FOREIGN KEY (added_by) REFERENCES public.users(id),
  CONSTRAINT audit_team_members_audit_id_fkey FOREIGN KEY (audit_id) REFERENCES public.audits(id),
  CONSTRAINT audit_team_members_removed_by_fkey FOREIGN KEY (removed_by) REFERENCES public.users(id)
);
CREATE TABLE public.audit_time_entries (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  audit_id uuid NOT NULL,
  user_id uuid NOT NULL,
  audit_phase_id uuid,
  entry_date date NOT NULL,
  hours_worked numeric NOT NULL CHECK (hours_worked > 0::numeric AND hours_worked <= 24::numeric),
  activity_description text NOT NULL,
  billable boolean DEFAULT true,
  approved boolean DEFAULT false,
  approved_by uuid,
  approved_at timestamp with time zone,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT audit_time_entries_pkey PRIMARY KEY (id),
  CONSTRAINT audit_time_entries_approved_by_fkey FOREIGN KEY (approved_by) REFERENCES public.users(id),
  CONSTRAINT audit_time_entries_audit_id_fkey FOREIGN KEY (audit_id) REFERENCES public.audits(id),
  CONSTRAINT audit_time_entries_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.users(id),
  CONSTRAINT audit_time_entries_audit_phase_id_fkey FOREIGN KEY (audit_phase_id) REFERENCES public.audit_phases(id)
);
CREATE TABLE public.audits (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  title character varying NOT NULL,
  description text,
  audit_type character varying NOT NULL CHECK (audit_type::text = ANY (ARRAY['internal'::character varying, 'external'::character varying, 'compliance'::character varying, 'operational'::character varying, 'financial'::character varying, 'it'::character varying, 'quality'::character varying, 'environmental'::character varying]::text[])),
  status character varying NOT NULL DEFAULT 'draft'::character varying CHECK (status::text = ANY (ARRAY['draft'::character varying, 'planning'::character varying, 'in_progress'::character varying, 'testing'::character varying, 'reporting'::character varying, 'completed'::character varying, 'cancelled'::character varying, 'on_hold'::character varying]::text[])),
  business_unit_id uuid,
  lead_auditor_id uuid,
  team_members ARRAY DEFAULT '{}'::uuid[],
  start_date date,
  end_date date,
  planned_hours numeric,
  actual_hours numeric,
  objectives ARRAY,
  scope text,
  methodology text,
  ai_generated boolean DEFAULT false,
  ai_model_used character varying,
  approval_status character varying DEFAULT 'draft'::character varying CHECK (approval_status::text = ANY (ARRAY['draft'::character varying, 'pending_approval'::character varying, 'approved'::character varying, 'rejected'::character varying, 'revision_required'::character varying]::text[])),
  created_by uuid,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  audit_number character varying UNIQUE,
  priority USER-DEFINED DEFAULT 'medium'::priority_level,
  department character varying,
  location character varying,
  supervisor_auditor_id uuid,
  assigned_by uuid,
  audit_criteria text,
  exclusions text,
  ai_confidence_score numeric,
  approval_notes text,
  inherent_risk USER-DEFINED,
  residual_risk USER-DEFINED,
  control_risk USER-DEFINED,
  version integer DEFAULT 1,
  is_deleted boolean DEFAULT false,
  parent_audit_id uuid,
  audit_program_id uuid,
  external_audit_firm character varying,
  external_reference character varying,
  regulatory_requirement character varying,
  deleted_at timestamp with time zone,
  approved_by uuid,
  approved_at timestamp with time zone,
  actual_start_date date,
  actual_end_date date,
  CONSTRAINT audits_pkey PRIMARY KEY (id),
  CONSTRAINT audits_approved_by_fkey FOREIGN KEY (approved_by) REFERENCES public.users(id),
  CONSTRAINT audits_parent_audit_id_fkey FOREIGN KEY (parent_audit_id) REFERENCES public.audits(id),
  CONSTRAINT audits_assigned_by_fkey FOREIGN KEY (assigned_by) REFERENCES public.users(id),
  CONSTRAINT audits_supervisor_auditor_id_fkey FOREIGN KEY (supervisor_auditor_id) REFERENCES public.users(id),
  CONSTRAINT audits_created_by_fkey FOREIGN KEY (created_by) REFERENCES public.users(id),
  CONSTRAINT audits_business_unit_id_fkey FOREIGN KEY (business_unit_id) REFERENCES public.business_units(id),
  CONSTRAINT audits_lead_auditor_id_fkey FOREIGN KEY (lead_auditor_id) REFERENCES public.users(id)
);
CREATE TABLE public.business_units (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  name character varying NOT NULL,
  code character varying NOT NULL UNIQUE,
  description text,
  manager_id uuid,
  parent_id uuid,
  is_active boolean DEFAULT true,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT business_units_pkey PRIMARY KEY (id),
  CONSTRAINT fk_business_units_manager FOREIGN KEY (manager_id) REFERENCES public.users(id),
  CONSTRAINT business_units_parent_id_fkey FOREIGN KEY (parent_id) REFERENCES public.business_units(id)
);
CREATE TABLE public.comments (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  entity_type character varying NOT NULL CHECK (entity_type::text = ANY (ARRAY['audit'::character varying, 'finding'::character varying, 'control'::character varying, 'risk'::character varying]::text[])),
  entity_id uuid NOT NULL,
  user_id uuid NOT NULL,
  content text NOT NULL,
  is_internal boolean DEFAULT true,
  attachments ARRAY,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT comments_pkey PRIMARY KEY (id),
  CONSTRAINT comments_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.users(id)
);
CREATE TABLE public.control_sets (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  audit_id uuid,
  name character varying NOT NULL CHECK (length(TRIM(BOTH FROM name)) > 0),
  description text,
  framework character varying NOT NULL CHECK (length(TRIM(BOTH FROM framework)) > 0),
  controls_count integer DEFAULT 0 CHECK (controls_count >= 0),
  ai_generated boolean DEFAULT false,
  created_by uuid,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  is_deleted boolean DEFAULT false,
  CONSTRAINT control_sets_pkey PRIMARY KEY (id),
  CONSTRAINT fk_control_sets_audit_id FOREIGN KEY (audit_id) REFERENCES public.audits(id),
  CONSTRAINT fk_control_sets_created_by FOREIGN KEY (created_by) REFERENCES public.users(id)
);
CREATE TABLE public.control_tests (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  control_id uuid NOT NULL,
  audit_id uuid,
  tester_id uuid,
  test_date date NOT NULL,
  test_result character varying NOT NULL CHECK (test_result::text = ANY (ARRAY['passed'::character varying, 'failed'::character varying, 'not_applicable'::character varying, 'not_tested'::character varying]::text[])),
  sample_size integer CHECK (sample_size IS NULL OR sample_size > 0),
  exceptions_noted integer DEFAULT 0 CHECK (exceptions_noted >= 0),
  testing_notes text,
  evidence_files ARRAY,
  created_by uuid,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT control_tests_pkey PRIMARY KEY (id),
  CONSTRAINT fk_control_tests_created_by FOREIGN KEY (created_by) REFERENCES public.users(id),
  CONSTRAINT control_tests_control_id_fkey FOREIGN KEY (control_id) REFERENCES public.controls(id),
  CONSTRAINT fk_control_tests_audit_id FOREIGN KEY (audit_id) REFERENCES public.audits(id),
  CONSTRAINT fk_control_tests_tester_id FOREIGN KEY (tester_id) REFERENCES public.users(id)
);
CREATE TABLE public.controls (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  control_set_id uuid NOT NULL,
  audit_id uuid,
  control_code character varying NOT NULL CHECK (length(TRIM(BOTH FROM control_code)) > 0),
  title character varying NOT NULL CHECK (length(TRIM(BOTH FROM title)) > 0),
  description text NOT NULL CHECK (length(TRIM(BOTH FROM description)) > 0),
  control_type USER-DEFINED NOT NULL,
  frequency USER-DEFINED NOT NULL,
  process_area character varying NOT NULL CHECK (length(TRIM(BOTH FROM process_area)) > 0),
  owner_id uuid,
  testing_procedure text NOT NULL CHECK (length(TRIM(BOTH FROM testing_procedure)) > 0),
  evidence_requirements text NOT NULL CHECK (length(TRIM(BOTH FROM evidence_requirements)) > 0),
  effectiveness USER-DEFINED DEFAULT 'not_tested'::control_effectiveness_enum,
  last_tested_date date,
  next_test_date date,
  is_automated boolean DEFAULT false,
  ai_generated boolean DEFAULT false,
  created_by uuid,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  is_deleted boolean DEFAULT false,
  evidence_requirements_text text,
  generation_prompt text,
  generated_at timestamp with time zone,
  test_results text,
  CONSTRAINT controls_pkey PRIMARY KEY (id),
  CONSTRAINT controls_control_set_id_fkey FOREIGN KEY (control_set_id) REFERENCES public.control_sets(id),
  CONSTRAINT fk_controls_owner_id FOREIGN KEY (owner_id) REFERENCES public.users(id),
  CONSTRAINT fk_controls_audit_id FOREIGN KEY (audit_id) REFERENCES public.audits(id),
  CONSTRAINT fk_controls_created_by FOREIGN KEY (created_by) REFERENCES public.users(id)
);
CREATE TABLE public.evidence_files (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  file_name character varying NOT NULL,
  file_size bigint NOT NULL,
  file_type character varying NOT NULL,
  file_path text NOT NULL,
  entity_type character varying NOT NULL CHECK (entity_type::text = ANY (ARRAY['audit'::character varying, 'finding'::character varying, 'control'::character varying, 'test'::character varying]::text[])),
  entity_id uuid NOT NULL,
  uploaded_by uuid NOT NULL,
  uploaded_at timestamp with time zone DEFAULT now(),
  CONSTRAINT evidence_files_pkey PRIMARY KEY (id),
  CONSTRAINT evidence_files_uploaded_by_fkey FOREIGN KEY (uploaded_by) REFERENCES public.users(id)
);
CREATE TABLE public.findings (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  audit_id uuid NOT NULL,
  control_id uuid,
  title character varying NOT NULL CHECK (char_length(title::text) <= 200),
  description text,
  severity character varying NOT NULL CHECK (severity::text = ANY (ARRAY['low'::character varying, 'medium'::character varying, 'high'::character varying, 'critical'::character varying]::text[])),
  status character varying DEFAULT 'open'::character varying CHECK (status::text = ANY (ARRAY['open'::character varying, 'in_progress'::character varying, 'resolved'::character varying, 'closed'::character varying, 'deferred'::character varying]::text[])),
  risk_rating character varying NOT NULL CHECK (risk_rating::text = ANY (ARRAY['low'::character varying, 'medium'::character varying, 'high'::character varying, 'critical'::character varying]::text[])),
  business_impact text,
  root_cause text,
  recommendation text,
  management_response text,
  assigned_to uuid,
  due_date date,
  evidence_files ARRAY,
  ai_generated boolean DEFAULT false,
  created_by uuid,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  control_failure boolean DEFAULT false,
  audit_reference character varying CHECK (audit_reference IS NULL OR char_length(audit_reference::text) <= 120),
  workflow_status USER-DEFINED DEFAULT 'draft'::finding_status,
  tags ARRAY DEFAULT ARRAY[]::text[],
  attachments jsonb DEFAULT '[]'::jsonb,
  internal_owner_id uuid,
  remediation_owner_id uuid,
  remediation_due_date date,
  updated_by uuid,
  submitted_at timestamp with time zone,
  reviewed_at timestamp with time zone,
  opened_at timestamp with time zone,
  remediated_at timestamp with time zone,
  closed_at timestamp with time zone,
  CONSTRAINT findings_pkey PRIMARY KEY (id),
  CONSTRAINT findings_audit_id_fkey FOREIGN KEY (audit_id) REFERENCES public.audits(id),
  CONSTRAINT findings_assigned_to_fkey FOREIGN KEY (assigned_to) REFERENCES public.users(id),
  CONSTRAINT findings_created_by_fkey FOREIGN KEY (created_by) REFERENCES public.users(id),
  CONSTRAINT findings_internal_owner_id_fkey FOREIGN KEY (internal_owner_id) REFERENCES public.users(id),
  CONSTRAINT findings_remediation_owner_id_fkey FOREIGN KEY (remediation_owner_id) REFERENCES public.users(id),
  CONSTRAINT findings_updated_by_fkey FOREIGN KEY (updated_by) REFERENCES public.users(id)
);
CREATE TABLE public.findings_saved_views (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  user_id uuid NOT NULL,
  name character varying NOT NULL,
  filters jsonb NOT NULL DEFAULT '{}'::jsonb,
  is_default boolean DEFAULT false,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT findings_saved_views_pkey PRIMARY KEY (id),
  CONSTRAINT findings_saved_views_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.users(id)
);
CREATE TABLE public.findings_status_history (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  finding_id uuid NOT NULL,
  old_status USER-DEFINED,
  new_status USER-DEFINED NOT NULL,
  changed_by uuid,
  changed_at timestamp with time zone NOT NULL DEFAULT now(),
  change_reason text,
  CONSTRAINT findings_status_history_pkey PRIMARY KEY (id),
  CONSTRAINT findings_status_history_changed_by_fkey FOREIGN KEY (changed_by) REFERENCES public.users(id),
  CONSTRAINT findings_status_history_finding_id_fkey FOREIGN KEY (finding_id) REFERENCES public.findings(id)
);
CREATE TABLE public.findings_versions (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  finding_id uuid NOT NULL,
  version integer NOT NULL,
  changed_by uuid,
  changed_at timestamp with time zone NOT NULL DEFAULT now(),
  diff jsonb,
  snapshot jsonb NOT NULL,
  CONSTRAINT findings_versions_pkey PRIMARY KEY (id),
  CONSTRAINT findings_versions_changed_by_fkey FOREIGN KEY (changed_by) REFERENCES public.users(id),
  CONSTRAINT findings_versions_finding_id_fkey FOREIGN KEY (finding_id) REFERENCES public.findings(id)
);
CREATE TABLE public.notifications (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  user_id uuid NOT NULL,
  type character varying NOT NULL CHECK (type::text = ANY (ARRAY['audit_assigned'::character varying, 'finding_created'::character varying, 'approval_required'::character varying, 'due_date_reminder'::character varying, 'test_overdue'::character varying, 'comment_added'::character varying]::text[])),
  title character varying NOT NULL,
  message text NOT NULL,
  entity_type character varying,
  entity_id uuid,
  is_read boolean DEFAULT false,
  created_at timestamp with time zone DEFAULT now(),
  CONSTRAINT notifications_pkey PRIMARY KEY (id),
  CONSTRAINT notifications_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.users(id)
);
CREATE TABLE public.risk_appetite (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  business_unit_id uuid,
  risk_category_id uuid,
  appetite_level character varying NOT NULL CHECK (appetite_level::text = ANY (ARRAY['very_low'::character varying, 'low'::character varying, 'medium'::character varying, 'high'::character varying, 'very_high'::character varying]::text[])),
  tolerance_threshold integer CHECK (tolerance_threshold >= 1 AND tolerance_threshold <= 25),
  description text,
  review_frequency character varying DEFAULT 'annually'::character varying CHECK (review_frequency::text = ANY (ARRAY['monthly'::character varying, 'quarterly'::character varying, 'semi_annually'::character varying, 'annually'::character varying]::text[])),
  approved_by uuid,
  approved_at timestamp with time zone,
  effective_from date NOT NULL,
  effective_to date,
  is_active boolean DEFAULT true,
  created_by uuid,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT risk_appetite_pkey PRIMARY KEY (id),
  CONSTRAINT risk_appetite_created_by_fkey FOREIGN KEY (created_by) REFERENCES public.users(id),
  CONSTRAINT risk_appetite_approved_by_fkey FOREIGN KEY (approved_by) REFERENCES public.users(id),
  CONSTRAINT risk_appetite_risk_category_id_fkey FOREIGN KEY (risk_category_id) REFERENCES public.risk_categories(id),
  CONSTRAINT risk_appetite_business_unit_id_fkey FOREIGN KEY (business_unit_id) REFERENCES public.business_units(id)
);
CREATE TABLE public.risk_assessments (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  risk_id uuid NOT NULL,
  assessment_date date NOT NULL DEFAULT CURRENT_DATE,
  assessor_id uuid,
  assessment_type character varying DEFAULT 'periodic'::character varying CHECK (assessment_type::text = ANY (ARRAY['initial'::character varying, 'periodic'::character varying, 'triggered'::character varying, 'ad_hoc'::character varying]::text[])),
  probability integer NOT NULL CHECK (probability >= 1 AND probability <= 5),
  impact integer NOT NULL CHECK (impact >= 1 AND impact <= 5),
  risk_score integer NOT NULL,
  risk_level character varying NOT NULL CHECK (risk_level::text = ANY (ARRAY['low'::character varying, 'medium'::character varying, 'high'::character varying, 'critical'::character varying]::text[])),
  assessment_notes text,
  key_assumptions text,
  data_sources text,
  confidence_level character varying DEFAULT 'medium'::character varying CHECK (confidence_level::text = ANY (ARRAY['low'::character varying, 'medium'::character varying, 'high'::character varying]::text[])),
  review_trigger character varying,
  attachments jsonb DEFAULT '[]'::jsonb,
  created_by uuid,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT risk_assessments_pkey PRIMARY KEY (id),
  CONSTRAINT risk_assessments_created_by_fkey FOREIGN KEY (created_by) REFERENCES public.users(id),
  CONSTRAINT risk_assessments_assessor_id_fkey FOREIGN KEY (assessor_id) REFERENCES public.users(id),
  CONSTRAINT risk_assessments_risk_id_fkey FOREIGN KEY (risk_id) REFERENCES public.risks(id)
);
CREATE TABLE public.risk_categories (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  name character varying NOT NULL UNIQUE,
  description text,
  color character varying DEFAULT '#6B7280'::character varying,
  parent_id uuid,
  is_active boolean DEFAULT true,
  sort_order integer DEFAULT 0,
  created_by uuid,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT risk_categories_pkey PRIMARY KEY (id),
  CONSTRAINT risk_categories_created_by_fkey FOREIGN KEY (created_by) REFERENCES public.users(id),
  CONSTRAINT risk_categories_parent_id_fkey FOREIGN KEY (parent_id) REFERENCES public.risk_categories(id)
);
CREATE TABLE public.risk_controls (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  risk_id uuid NOT NULL,
  control_id uuid NOT NULL,
  control_effectiveness character varying DEFAULT 'effective'::character varying CHECK (control_effectiveness::text = ANY (ARRAY['effective'::character varying, 'partially_effective'::character varying, 'ineffective'::character varying, 'not_tested'::character varying]::text[])),
  coverage_level character varying DEFAULT 'full'::character varying CHECK (coverage_level::text = ANY (ARRAY['full'::character varying, 'partial'::character varying, 'minimal'::character varying]::text[])),
  control_type character varying DEFAULT 'mitigating'::character varying CHECK (control_type::text = ANY (ARRAY['preventive'::character varying, 'detective'::character varying, 'corrective'::character varying, 'mitigating'::character varying]::text[])),
  relationship_notes text,
  last_tested_date date,
  next_test_date date,
  created_by uuid,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT risk_controls_pkey PRIMARY KEY (id),
  CONSTRAINT risk_controls_created_by_fkey FOREIGN KEY (created_by) REFERENCES public.users(id),
  CONSTRAINT risk_controls_risk_id_fkey FOREIGN KEY (risk_id) REFERENCES public.risks(id),
  CONSTRAINT risk_controls_control_id_fkey FOREIGN KEY (control_id) REFERENCES public.controls(id)
);
CREATE TABLE public.risk_incidents (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  risk_id uuid NOT NULL,
  incident_title character varying NOT NULL,
  incident_description text NOT NULL,
  incident_date date NOT NULL,
  discovered_date date DEFAULT CURRENT_DATE,
  reported_by uuid,
  severity character varying NOT NULL CHECK (severity::text = ANY (ARRAY['low'::character varying, 'medium'::character varying, 'high'::character varying, 'critical'::character varying]::text[])),
  actual_impact text,
  financial_impact numeric,
  currency character varying DEFAULT 'USD'::character varying,
  lessons_learned text,
  corrective_actions text,
  preventive_measures text,
  status character varying DEFAULT 'open'::character varying CHECK (status::text = ANY (ARRAY['open'::character varying, 'investigating'::character varying, 'resolved'::character varying, 'closed'::character varying]::text[])),
  resolution_date date,
  attachments jsonb DEFAULT '[]'::jsonb,
  created_by uuid,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT risk_incidents_pkey PRIMARY KEY (id),
  CONSTRAINT risk_incidents_created_by_fkey FOREIGN KEY (created_by) REFERENCES public.users(id),
  CONSTRAINT risk_incidents_reported_by_fkey FOREIGN KEY (reported_by) REFERENCES public.users(id),
  CONSTRAINT risk_incidents_risk_id_fkey FOREIGN KEY (risk_id) REFERENCES public.risks(id)
);
CREATE TABLE public.risk_matrices (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  name character varying NOT NULL,
  description text,
  probability_labels jsonb NOT NULL DEFAULT '[{"label": "Very Low", "value": 1, "description": "Less than 5% chance"}, {"label": "Low", "value": 2, "description": "5-25% chance"}, {"label": "Medium", "value": 3, "description": "25-50% chance"}, {"label": "High", "value": 4, "description": "50-75% chance"}, {"label": "Very High", "value": 5, "description": "More than 75% chance"}]'::jsonb,
  impact_labels jsonb NOT NULL DEFAULT '[{"label": "Minimal", "value": 1, "description": "Minor operational impact"}, {"label": "Minor", "value": 2, "description": "Limited operational impact"}, {"label": "Moderate", "value": 3, "description": "Significant operational impact"}, {"label": "Major", "value": 4, "description": "Severe operational impact"}, {"label": "Catastrophic", "value": 5, "description": "Critical operational impact"}]'::jsonb,
  scoring_matrix jsonb NOT NULL DEFAULT '{"1": {"1": {"level": "low", "score": 1}, "2": {"level": "low", "score": 2}, "3": {"level": "low", "score": 3}, "4": {"level": "medium", "score": 4}, "5": {"level": "medium", "score": 5}}, "2": {"1": {"level": "low", "score": 2}, "2": {"level": "medium", "score": 4}, "3": {"level": "medium", "score": 6}, "4": {"level": "medium", "score": 8}, "5": {"level": "high", "score": 10}}, "3": {"1": {"level": "low", "score": 3}, "2": {"level": "medium", "score": 6}, "3": {"level": "medium", "score": 9}, "4": {"level": "high", "score": 12}, "5": {"level": "high", "score": 15}}, "4": {"1": {"level": "medium", "score": 4}, "2": {"level": "medium", "score": 8}, "3": {"level": "high", "score": 12}, "4": {"level": "high", "score": 16}, "5": {"level": "critical", "score": 20}}, "5": {"1": {"level": "medium", "score": 5}, "2": {"level": "high", "score": 10}, "3": {"level": "high", "score": 15}, "4": {"level": "critical", "score": 20}, "5": {"level": "critical", "score": 25}}}'::jsonb,
  is_default boolean DEFAULT false,
  is_active boolean DEFAULT true,
  created_by uuid,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT risk_matrices_pkey PRIMARY KEY (id),
  CONSTRAINT risk_matrices_created_by_fkey FOREIGN KEY (created_by) REFERENCES public.users(id)
);
CREATE TABLE public.risk_reviews (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  risk_id uuid NOT NULL,
  review_date date NOT NULL DEFAULT CURRENT_DATE,
  reviewer_id uuid NOT NULL,
  review_type character varying DEFAULT 'periodic'::character varying CHECK (review_type::text = ANY (ARRAY['periodic'::character varying, 'triggered'::character varying, 'incident_based'::character varying, 'audit_based'::character varying]::text[])),
  review_outcome character varying DEFAULT 'no_change'::character varying CHECK (review_outcome::text = ANY (ARRAY['no_change'::character varying, 'updated'::character varying, 'escalated'::character varying, 'closed'::character varying, 'transferred'::character varying]::text[])),
  risk_status_before character varying,
  risk_status_after character varying,
  probability_before integer,
  probability_after integer,
  impact_before integer,
  impact_after integer,
  changes_made text,
  review_notes text,
  recommendations text,
  next_review_date date,
  attachments jsonb DEFAULT '[]'::jsonb,
  created_by uuid,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT risk_reviews_pkey PRIMARY KEY (id),
  CONSTRAINT risk_reviews_created_by_fkey FOREIGN KEY (created_by) REFERENCES public.users(id),
  CONSTRAINT risk_reviews_risk_id_fkey FOREIGN KEY (risk_id) REFERENCES public.risks(id),
  CONSTRAINT risk_reviews_reviewer_id_fkey FOREIGN KEY (reviewer_id) REFERENCES public.users(id)
);
CREATE TABLE public.risk_treatments (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  risk_id uuid NOT NULL,
  treatment_type character varying NOT NULL CHECK (treatment_type::text = ANY (ARRAY['mitigate'::character varying, 'accept'::character varying, 'transfer'::character varying, 'avoid'::character varying, 'monitor'::character varying]::text[])),
  title character varying NOT NULL,
  description text NOT NULL,
  treatment_strategy text,
  cost_estimate numeric,
  currency character varying DEFAULT 'USD'::character varying,
  assigned_to uuid,
  responsible_department character varying,
  priority character varying DEFAULT 'medium'::character varying CHECK (priority::text = ANY (ARRAY['low'::character varying, 'medium'::character varying, 'high'::character varying, 'critical'::character varying]::text[])),
  status character varying DEFAULT 'planned'::character varying CHECK (status::text = ANY (ARRAY['planned'::character varying, 'in_progress'::character varying, 'completed'::character varying, 'cancelled'::character varying, 'on_hold'::character varying, 'overdue'::character varying]::text[])),
  start_date date,
  target_date date,
  completed_date date,
  effectiveness_rating integer CHECK (effectiveness_rating >= 1 AND effectiveness_rating <= 5),
  effectiveness_notes text,
  success_criteria text,
  kpis jsonb DEFAULT '[]'::jsonb,
  dependencies text,
  constraints_limitations text,
  attachments jsonb DEFAULT '[]'::jsonb,
  created_by uuid,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT risk_treatments_pkey PRIMARY KEY (id),
  CONSTRAINT risk_treatments_created_by_fkey FOREIGN KEY (created_by) REFERENCES public.users(id),
  CONSTRAINT risk_treatments_assigned_to_fkey FOREIGN KEY (assigned_to) REFERENCES public.users(id),
  CONSTRAINT risk_treatments_risk_id_fkey FOREIGN KEY (risk_id) REFERENCES public.risks(id)
);
CREATE TABLE public.risk_workflows (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  risk_id uuid NOT NULL,
  workflow_type character varying NOT NULL CHECK (workflow_type::text = ANY (ARRAY['approval'::character varying, 'review'::character varying, 'escalation'::character varying, 'notification'::character varying]::text[])),
  current_step integer DEFAULT 1,
  total_steps integer NOT NULL,
  status character varying DEFAULT 'pending'::character varying CHECK (status::text = ANY (ARRAY['pending'::character varying, 'in_progress'::character varying, 'approved'::character varying, 'rejected'::character varying, 'cancelled'::character varying]::text[])),
  workflow_data jsonb NOT NULL DEFAULT '{}'::jsonb,
  initiated_by uuid,
  initiated_at timestamp with time zone DEFAULT now(),
  completed_at timestamp with time zone,
  comments text,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT risk_workflows_pkey PRIMARY KEY (id),
  CONSTRAINT risk_workflows_risk_id_fkey FOREIGN KEY (risk_id) REFERENCES public.risks(id),
  CONSTRAINT risk_workflows_initiated_by_fkey FOREIGN KEY (initiated_by) REFERENCES public.users(id)
);
CREATE TABLE public.risks (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  title character varying NOT NULL,
  description text,
  category character varying NOT NULL,
  business_unit_id uuid,
  probability integer CHECK (probability >= 1 AND probability <= 5),
  impact integer CHECK (impact >= 1 AND impact <= 5),
  risk_level character varying NOT NULL CHECK (risk_level::text = ANY (ARRAY['low'::character varying, 'medium'::character varying, 'high'::character varying, 'critical'::character varying]::text[])),
  inherent_risk_score integer,
  residual_risk_score integer,
  mitigation_strategy text,
  owner_id uuid,
  status character varying DEFAULT 'identified'::character varying CHECK (status::text = ANY (ARRAY['identified'::character varying, 'assessed'::character varying, 'treating'::character varying, 'monitoring'::character varying, 'accepted'::character varying, 'transferred'::character varying, 'avoided'::character varying, 'closed'::character varying]::text[])),
  ai_generated boolean DEFAULT false,
  created_by uuid,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  risk_category_id uuid,
  risk_matrix_id uuid,
  risk_source character varying,
  likelihood_trend character varying DEFAULT 'stable'::character varying CHECK (likelihood_trend::text = ANY (ARRAY['increasing'::character varying, 'decreasing'::character varying, 'stable'::character varying]::text[])),
  impact_trend character varying DEFAULT 'stable'::character varying CHECK (impact_trend::text = ANY (ARRAY['increasing'::character varying, 'decreasing'::character varying, 'stable'::character varying]::text[])),
  target_probability integer CHECK (target_probability >= 1 AND target_probability <= 5),
  target_impact integer CHECK (target_impact >= 1 AND target_impact <= 5),
  target_risk_score integer,
  target_date date,
  escalation_criteria text,
  last_review_date date,
  next_review_date date,
  review_frequency character varying DEFAULT 'quarterly'::character varying CHECK (review_frequency::text = ANY (ARRAY['weekly'::character varying, 'monthly'::character varying, 'quarterly'::character varying, 'semi_annually'::character varying, 'annually'::character varying]::text[])),
  tags ARRAY,
  external_reference character varying,
  attachments jsonb DEFAULT '[]'::jsonb,
  CONSTRAINT risks_pkey PRIMARY KEY (id),
  CONSTRAINT risks_risk_category_id_fkey FOREIGN KEY (risk_category_id) REFERENCES public.risk_categories(id),
  CONSTRAINT risks_business_unit_id_fkey FOREIGN KEY (business_unit_id) REFERENCES public.business_units(id),
  CONSTRAINT risks_owner_id_fkey FOREIGN KEY (owner_id) REFERENCES public.users(id),
  CONSTRAINT risks_created_by_fkey FOREIGN KEY (created_by) REFERENCES public.users(id),
  CONSTRAINT risks_risk_matrix_id_fkey FOREIGN KEY (risk_matrix_id) REFERENCES public.risk_matrices(id)
);
CREATE TABLE public.users (
  id uuid NOT NULL,
  email character varying NOT NULL UNIQUE,
  first_name character varying NOT NULL,
  last_name character varying NOT NULL,
  role character varying NOT NULL DEFAULT 'viewer'::character varying CHECK (role::text = ANY (ARRAY['super_admin'::character varying, 'admin'::character varying, 'cro'::character varying, 'supervisor_auditor'::character varying, 'auditor'::character varying, 'reviewer'::character varying, 'viewer'::character varying, 'business_unit_manager'::character varying, 'business_unit_user'::character varying]::text[])),
  department character varying,
  business_unit_id uuid,
  avatar_url text,
  is_active boolean DEFAULT true,
  last_login timestamp with time zone,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT users_pkey PRIMARY KEY (id),
  CONSTRAINT users_id_fkey FOREIGN KEY (id) REFERENCES auth.users(id),
  CONSTRAINT users_business_unit_id_fkey FOREIGN KEY (business_unit_id) REFERENCES public.business_units(id)
);
CREATE TABLE public.workflow_steps (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  workflow_id uuid NOT NULL,
  step_order integer NOT NULL,
  step_name character varying NOT NULL,
  assignee_role character varying NOT NULL,
  assignee_id uuid,
  required boolean DEFAULT true,
  status character varying DEFAULT 'pending'::character varying CHECK (status::text = ANY (ARRAY['pending'::character varying, 'completed'::character varying, 'skipped'::character varying]::text[])),
  completed_at timestamp with time zone,
  completed_by uuid,
  comments text,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT workflow_steps_pkey PRIMARY KEY (id),
  CONSTRAINT workflow_steps_completed_by_fkey FOREIGN KEY (completed_by) REFERENCES public.users(id),
  CONSTRAINT workflow_steps_workflow_id_fkey FOREIGN KEY (workflow_id) REFERENCES public.workflows(id),
  CONSTRAINT workflow_steps_assignee_id_fkey FOREIGN KEY (assignee_id) REFERENCES public.users(id)
);
CREATE TABLE public.workflows (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  name character varying NOT NULL,
  description text,
  entity_type character varying NOT NULL CHECK (entity_type::text = ANY (ARRAY['audit'::character varying, 'finding'::character varying, 'control'::character varying, 'risk'::character varying]::text[])),
  is_active boolean DEFAULT true,
  created_by uuid,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT workflows_pkey PRIMARY KEY (id),
  CONSTRAINT workflows_created_by_fkey FOREIGN KEY (created_by) REFERENCES public.users(id)
);
);