import type { AIGenerationRequest } from "./types";

export class AIReportingService {
  private buildReportingPrompt(request: AIGenerationRequest): string {
    const { fieldType, auditData, context } = request;

    // Handle undefined auditData gracefully
    const safeAuditData = auditData || {};
    const auditInfo = `
Audit Information:
- Title: ${safeAuditData.title || "Not specified"}
- Type: ${safeAuditData.audit_type || "Not specified"}
- Business Unit: ${safeAuditData.business_unit || "Not specified"}
- Existing Scope: ${safeAuditData.scope || "Not specified"}
    `.trim();

    switch (fieldType) {
      case "chart_data":
        return `You are an expert in data visualization and analytics. Generate comprehensive chart data based on the following information:

${auditInfo}

Context: ${context}

Requirements:
- Create detailed chart data with appropriate metrics and values
- Ensure the data is specifically relevant to "${safeAuditData.title || "the analysis"}"
- Include data points, labels, and categories suitable for visualization
- Provide data in a structured format that can be easily charted
- Include both quantitative metrics and qualitative insights
- Use professional data presentation terminology
- Keep it between 200-400 words
- Make it specific to the analysis type and business unit
- Include data sources and calculation methodologies

Generate only the chart data description, no additional formatting or explanations.`;

      case "table_data":
        return `You are an expert in data organization and tabular presentation. Generate comprehensive table data based on the following information:

${auditInfo}

Context: ${context}

Requirements:
- Create detailed table structure with appropriate columns and data
- Ensure the data is specifically relevant to "${safeAuditData.title || "the analysis"}"
- Include column headers, data types, and sample data rows
- Provide data that can be organized in a tabular format
- Include both quantitative and qualitative data points
- Use professional data organization terminology
- Keep it between 200-400 words
- Make it specific to the analysis type and business unit
- Include data validation rules and formatting guidelines

Generate only the table data description, no additional formatting or explanations.`;

      case "control_evaluation":
        return `You are an expert in control evaluation and effectiveness assessment. Generate comprehensive control evaluation based on the following information:

${auditInfo}

Context: ${context}

Requirements:
- Create detailed control evaluation methodology and criteria
- Ensure the evaluation is specifically relevant to "${safeAuditData.title || "the controls"}"
- Include control effectiveness assessment and testing procedures
- Provide evaluation metrics and performance indicators
- Use professional control evaluation terminology
- Keep it between 200-400 words
- Make it specific to the control framework and business unit
- Include control gaps identification and remediation recommendations

Generate only the control evaluation text, no additional formatting or explanations.`;

      default:
        return `You are an expert in governance, risk, and compliance (GRC) reporting and analytics. Generate comprehensive reporting content based on the following information:

${auditInfo}

Context: ${context}

Requirements:
- Create detailed, professional reporting content relevant to "${safeAuditData.title || "the report"}"
- Ensure the content is specifically tailored to the GRC reporting context and requirements
- Use professional reporting terminology appropriate to the field
- Keep it between 200-500 words
- Make it specific to the business unit and reporting context provided
- Include actionable insights, metrics, and recommendations where applicable
- Structure the content for clear reporting and presentation

Generate only the reporting content text, no additional formatting or explanations.`;
    }
  }

  buildChartDataPrompt(request: AIGenerationRequest): string {
    return this.buildReportingPrompt({ ...request, fieldType: "chart_data" });
  }

  buildTableDataPrompt(request: AIGenerationRequest): string {
    return this.buildReportingPrompt({ ...request, fieldType: "table_data" });
  }

  buildControlEvaluationPrompt(request: AIGenerationRequest): string {
    return this.buildReportingPrompt({ ...request, fieldType: "control_evaluation" });
  }

  generateReportStructure(title: string, sections: string[]): string {
    return `# ${title}

${sections.map((section, index) => `## ${index + 1}. ${section}`).join('\n\n')}

---
*Report generated by AI Assistant*
*Date: ${new Date().toLocaleDateString()}*
`;
  }

  generateExecutiveSummary(keyFindings: string[], recommendations: string[]): string {
    return `## Executive Summary

### Key Findings
${keyFindings.map(finding => `- ${finding}`).join('\n')}

### Recommendations
${recommendations.map(rec => `- ${rec}`).join('\n')}

### Next Steps
1. Review and validate findings
2. Implement recommended actions
3. Monitor progress and effectiveness
4. Schedule follow-up assessment
`;
  }

  generateMetricsDashboard(metrics: Array<{ name: string; value: number; target?: number; status: 'good' | 'warning' | 'critical' }>): string {
    const statusEmoji = {
      good: '✅',
      warning: '⚠️',
      critical: '❌'
    };

    return `## Metrics Dashboard

| Metric | Value | Target | Status |
|--------|-------|--------|--------|
${metrics.map(metric =>
  `| ${metric.name} | ${metric.value} | ${metric.target || 'N/A'} | ${statusEmoji[metric.status]} ${metric.status.toUpperCase()} |`
).join('\n')}

### Summary
- Total Metrics: ${metrics.length}
- Good: ${metrics.filter(m => m.status === 'good').length}
- Warning: ${metrics.filter(m => m.status === 'warning').length}
- Critical: ${metrics.filter(m => m.status === 'critical').length}
`;
  }

  generateComplianceMatrix(requirements: Array<{ control: string; status: 'compliant' | 'non-compliant' | 'partial'; evidence: string }>): string {
    const statusEmoji = {
      'compliant': '✅',
      'non-compliant': '❌',
      'partial': '⚠️'
    };

    return `## Compliance Matrix

| Control | Status | Evidence |
|---------|--------|----------|
${requirements.map(req =>
  `| ${req.control} | ${statusEmoji[req.status]} ${req.status.replace('-', ' ').toUpperCase()} | ${req.evidence} |`
).join('\n')}

### Compliance Summary
- Total Controls: ${requirements.length}
- Compliant: ${requirements.filter(r => r.status === 'compliant').length}
- Non-Compliant: ${requirements.filter(r => r.status === 'non-compliant').length}
- Partial: ${requirements.filter(r => r.status === 'partial').length}
- Overall Compliance: ${Math.round((requirements.filter(r => r.status === 'compliant').length / requirements.length) * 100)}%
`;
  }

  generateRiskHeatmap(risks: Array<{ category: string; likelihood: number; impact: number; level: 'low' | 'medium' | 'high' | 'critical' }>): string {
    const levelEmoji = {
      low: '🟢',
      medium: '🟡',
      high: '🟠',
      critical: '🔴'
    };

    return `## Risk Heatmap

| Risk Category | Likelihood | Impact | Risk Level |
|---------------|------------|--------|------------|
${risks.map(risk =>
  `| ${risk.category} | ${risk.likelihood}/5 | ${risk.impact}/5 | ${levelEmoji[risk.level]} ${risk.level.toUpperCase()} |`
).join('\n')}

### Risk Distribution
- Critical: ${risks.filter(r => r.level === 'critical').length}
- High: ${risks.filter(r => r.level === 'high').length}
- Medium: ${risks.filter(r => r.level === 'medium').length}
- Low: ${risks.filter(r => r.level === 'low').length}

### Risk Score Calculation
Risk Score = Likelihood × Impact
- 1-5: Low Risk
- 6-10: Medium Risk
- 11-20: High Risk
- 21-25: Critical Risk
`;
  }
}

export const aiReportingService = new AIReportingService();